GET http://localhost:5000/products

###
GET http://localhost:5000/products/4

###
POST http://localhost:5000/products
Content-Type: application/json

{
  "productName": "Denim Pants",
  "stock": 40,
}
###
PATCH http://localhost:5000/products/1
Content-Type: application/json

###
DELETE http://localhost:5000/products/1
Content-Type: application/json
