GET http://localhost:5000/products

###
GET http://localhost:5000/products/4

###
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "produk 1",
  "stock": 40,
  "price": 10000,
}
###
PATCH http://localhost:5000/products/1
Content-Type: application/json

###
DELETE http://localhost:5000/products/1
Content-Type: application/json

###
//get all users
GET http://localhost:5000/users
Content-Type: application/json

###
//get user by id
GET http://localhost:5000/users/0600a01a-0130-4692-a5ae-cbcfb405317e
Content-Type: application/json

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "cici",
  "email": "cici@gmail.com",
  "password": "12345",
  "confPassword": "12345",
  "role": "user"
}

###
PATCH http://localhost:5000/users/0600a01a-0130-4692-a5ae-cbcfb405317e
Content-Type: application/json

###
DELETE http://localhost:5000/users/91d9bd12-5d54-4142-bebf-b85a8bd79aff



###
//LOGIN ADMIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "caca@gmail.com",
  "password": "admin123"
}

###
//LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "cici@gmail.com",
  "password": "user123"
}

###
//ME
GET http://localhost:5000/me
Content-Type: application/json

###
DELETE http://localhost:5000/logout
Content-Type: application/json